services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - "${REDIS_PORT}:${REDIS_PORT2}"
    networks:
      - networks
    volumes:
      - './docker/redis/data:/data'
      - './docker/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro'
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf

networks:
  networks:
    driver: bridge

volumes:
  redis-data: